name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-nad-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Use pnpm
        run: npm install -g pnpm
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          folder: .output/server
          clean: true
